# Run with : spark-submit projet8_openpic.py
# spark-submit --packages databricks:spark-deep-learning:1.5.0-spark2.4-s_2.11 spark_app.py

##################################
# Creating SparkSession
##################################
# Import libraries
from pyspark.sql import SparkSession

# Creating SparkSession
spark = (SparkSession
            .builder
            .master("local")
            .appName("Projet 8")
            .getOrCreate()
)



##################################
# Loading images
##################################

IMAGE_PATH = "s3://p8-fruits/data"
IMAGE_PATH = "./data/Test/Apricot/**"


image_df = spark.read.format("image").load(IMAGE_PATH)


img_count = image_df.count()



##################################
# Dimensional reduction
##################################

from sparkdl import DeepImageFeaturizer

# Instanciate featurizer generated by ResNet50
featurizer = DeepImageFeaturizer(inputCol="image", outputCol="features", modelName="ResNet50")

# Apply the featurizer to our image_df DataFrame
features_df = img_count # for DEBUG
# features_df = featurizer.transform(image_df)

# Display results
print(features_df)
print("End of SparkApp")


####################################
# Log results to S3, using boto3
####################################
import json
import boto.s3, boto.s3.key


conn = boto.s3.connect_to_region("eu-west-3")
bucket = conn.get_bucket("p8-fruits")
key = boto.s3.key.Key(bucket, "features.txt")

key.set_contents_from_string(json.dumps(features_df, indent=2))
